# push!(LOAD_PATH,"E:/GitHub/ScTenifold.jl/src/");
using ScTenifold                          # obviously the tests use the ScTenifoldNet module... 
using Test                                # and the Base.Test module... 
tests = ["code_test1", "code_test2"]      # the test file names are stored as strings... 
for t in tests
  include("$(t).jl")                      # ... so that they can be evaluated in a loop 
end
